### PR TITLE
Feature user profile update

### LINKED ISSUE #3: UserProfile-Java
Implementar el endpoint que permita obtener y actualizar la información del perfil del usuario. Este endpoint debe estar protegido por autenticación y debe permitir la edición de datos del perfil.

### PR DESCRIPTION
**Pull request by DMFernandez96**
This PR implements the user profile update functionality. The endpoint allows the user to update their profile information such as name, email, preferences, location, etc.

- ### What is included:
- Created the `PUT /users/profile/{id}` endpoint to update the authenticated user's profile.
- Profile information includes name, email, location, preferences, and password (hashed).
- Implemented password hashing using BCrypt.

### Important Notes
- The functionality assumes that user authentication is already being handled by the authentication service (likely with JWT).
- The profile update will work as expected once authentication is integrated.

### CODE REVIEW

**Comment by DMFernandez96** [comment]
Agregados los nuevos cambios de develop

**Comment by EBDev81** [comment]
Hola. En UserRepository se pasa como parámetro en la interface UserRepository User y Long, pero debería ser User y String. Si lo dejamos como string aprobamos y hacemos merge

**Comment by DMFernandez96** [comment]
Hola! Ni lo vi, se me pasó completamente. Ya quedó arreglado!

**Review by EBDev81 — APPROVED** [review]

**Comment by EBDev81** [comment]
Perfecto, lo mergeo!!

**Pull request merged**
